<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PDINOTE-03" failures="4" tests="25" name="AllTests" time="259.617" errors="0" timestamp="2025-01-17T10:40:35 BRT">
  <testcase classname="base.LoginTest" name="testLogin" time="0.769"/>
  <testcase classname="ViewCare.ViewCareTest" name="testViewCare" time="5.742"/>
  <testcase classname="ViewCare.SalesPointTest" name="testOnlineEquipements" time="0.645"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFoundClientSalesPoint" time="0.231"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByClient" time="0.328"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByID" time="0.352"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByLastMessage" time="0.335"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByOnlineEquipment" time="0.316"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointBySalesPoint" time="0.319"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByServiceOrder" time="0.319"/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByTotalEquipment" time="0.317"/>
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfCLients" time="0.042">
    <failure type="java.lang.AssertionError" message="Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]
at ViewCare.SalesPointTest.testAssertNumberOfCLients(SalesPointTest.java:152)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testAssertNumberOfCLients -->
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfShowedResults" time="0.031"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testFetchListAndClickTheTestSalesPoint" time="0.278"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidateNameSalesPoint" time="0.065"/>
  <testcase classname="ViewCare.EnterSalesPointTest" name="testValidatesNumberOfOS" time="0.02">
    <failure type="java.lang.AssertionError" message="OS Number Does Not Match expected [2] but found [0]">
      <![CDATA[java.lang.AssertionError: OS Number Does Not Match expected [2] but found [0]
at ViewCare.EnterSalesPointTest.testValidatesNumberOfOS(EnterSalesPointTest.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testValidatesNumberOfOS -->
  <testcase classname="ViewCare.EnterControllerTest" name="testLastInfoFirstMonitorableIsValidController" time="0.55"/>
  <testcase classname="ViewCare.EnterControllerTest" name="testAccessEquipmentController" time="2.363"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfUsers" time="48.16"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfBiometry" time="23.762"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfTime" time="2.952"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testValidateNumberOfAccess" time="99.496"/>
  <testcase classname="ViewCare.ValidateControllerInformationTest" name="testExportAccess" time="30.749">
    <failure type="java.lang.AssertionError" message="Test ExportAccess: Failed, download did not start expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test ExportAccess: Failed, download did not start expected [true] but found [false]
at ViewCare.ValidateControllerInformationTest.testExportAccess(ValidateControllerInformationTest.java:121)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testExportAccess -->
  <testcase classname="ViewCare.ControllerTimeActionsTest" name="testCreateNewTime" time="16.338"/>
  <testcase classname="ViewCare.ControllerTimeActionsTest" name="testDeleteTime" time="7.585">
    <failure type="java.lang.AssertionError" message="Failed to delete new time. expected [ Horário excluído com sucesso. ] but found [Horário excluído com sucesso.]">
      <![CDATA[java.lang.AssertionError: Failed to delete new time. expected [ Horário excluído com sucesso. ] but found [Horário excluído com sucesso.]
at ViewCare.ControllerTimeActionsTest.testDeleteTime(ControllerTimeActionsTest.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteTime -->
</testsuite> <!-- AllTests -->
