<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PDINOTE-03" failures="1" tests="11" name="ViewCare.SalesPointTest" time="3.328" errors="0" timestamp="2025-01-20T11:25:48 BRT" skipped="0">
  <testcase classname="ViewCare.SalesPointTest" name="testOnlineEquipements" time="0.637"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByClient" time="0.350"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByID" time="0.336"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByLastMessage" time="0.317"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByOnlineEquipment" time="0.326"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByServiceOrder" time="0.323"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFoundClientSalesPoint" time="0.315"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointByTotalEquipment" time="0.329"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testFilterSalesPointBySalesPoint" time="0.326"/>
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfCLients" time="0.039">
    <failure message="Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Number of Shown Sales Points And Number of Sales Points Are Different expected [3] but found [4]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at ViewCare.SalesPointTest.testAssertNumberOfCLients(SalesPointTest.java:152)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testAssertNumberOfCLients -->
  <system-out/>
  <testcase classname="ViewCare.SalesPointTest" name="testAssertNumberOfShowedResults" time="0.030"/>
  <system-out/>
</testsuite> <!-- ViewCare.SalesPointTest -->
